<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-9I87QRH" failures="2" tests="10" name="Default test" time="0.82" errors="0" timestamp="2024-04-06T10:51:28 ICT">
  <testcase classname="Nhiem.SanPham.CapNhapTest" name="TC_CAPNHAT_01" time="0.087"/>
  <testcase classname="Nhiem.SanPham.CapNhapTest" name="TC_CAPNHAT_02" time="0.124"/>
  <testcase classname="Nhiem.SanPham.CapNhapTest" name="TC_CAPNHAT_03" time="0.08"/>
  <testcase classname="Nhiem.SanPham.CapNhapTest" name="TC_CAPNHAT_04" time="0.075"/>
  <testcase classname="Nhiem.SanPham.CapNhapTest" name="TC_CAPNHAT_05" time="0.093">
    <failure type="java.lang.AssertionError" message="expected [Tên sản phẩm không được chứa số] but found [Cập nhật thành công]">
      <![CDATA[java.lang.AssertionError: expected [Tên sản phẩm không được chứa số] but found [Cập nhật thành công]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Nhiem.SanPham.CapNhapTest.TC_CAPNHAT_05(CapNhapTest.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_CAPNHAT_05 -->
  <testcase classname="Nhiem.SanPham.CapNhapTest" name="TC_CAPNHAT_06" time="0.058"/>
  <testcase classname="Nhiem.SanPham.CapNhapTest" name="TC_CAPNHAT_07" time="0.021">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;model.SanPham.setTenSP(String)&amp;quot; because &amp;quot;sp&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "model.SanPham.setTenSP(String)" because "sp" is null
at Nhiem.SanPham.CapNhapTest.TC_CAPNHAT_07(CapNhapTest.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_CAPNHAT_07 -->
  <testcase classname="Nhiem.SanPham.CapNhapTest" name="TC_CAPNHAT_08" time="0.096"/>
  <testcase classname="Nhiem.SanPham.CapNhapTest" name="TC_CAPNHAT_09" time="0.061"/>
  <testcase classname="Nhiem.SanPham.CapNhapTest" name="TC_CAPNHAT_10" time="0.064"/>
</testsuite> <!-- Default test -->
